[2018-Nov-19 17:56:12][Autoplacement24in96][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Nov-19 17:56:12][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "c:\users\dforth\pycharmprojects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "c:\users\dforth\pycharmprojects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EGG-INFO\scripts\autoplacement_24_in_96.py", line 71, in _run
    (output_container_list[0], output_plate_layout[well_counter])))
IndexError: list index out of range

[2018-Nov-19 17:56:58][Autoplacement24in96][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Nov-19 17:56:58][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "c:\users\dforth\pycharmprojects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "c:\users\dforth\pycharmprojects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EGG-INFO\scripts\autoplacement_24_in_96.py", line 71, in _run
    (output_container_list[0], output_plate_layout[well_counter])))
IndexError: list index out of range

[2018-Nov-19 17:58:42][Autoplacement24in96][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Nov-19 17:58:42][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "c:\users\dforth\pycharmprojects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "c:\users\dforth\pycharmprojects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EGG-INFO\scripts\autoplacement_24_in_96.py", line 71, in _run
    (output_container_list[0], output_plate_layout[well_counter])))
IndexError: list index out of range

[2018-Nov-19 17:59:04][Autoplacement24in96][CRITICAL] Encountered a IndexError exception: list index out of range
[2018-Nov-19 17:59:04][Autoplacement24in96][ERROR] Stack trace below:
Traceback (most recent call last):
  File "c:\users\dforth\pycharmprojects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EPPs\common.py", line 133, in run
    return self._run()
  File "c:\users\dforth\pycharmprojects\untitled\venv\lib\site-packages\clarity_scripts-0.9.dev0-py3.6.egg\EGG-INFO\scripts\autoplacement_24_in_96.py", line 71, in _run
    (output_container_list[0], output_plate_layout[well_counter])))
IndexError: list index out of range

